### ISSUE TITLE
Couldn't find meta-data for provider with authority

### ISSUE THREAD

**Issue by kabirnayeem99** [kariot/pdf-invoice-generator#4]
Device: Android 10
Library Version: 1.0.0

Added these below in the manifest

`   <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="${applicationId}.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths" />
        </provider>
`

**Comment by kariot** [comment]
This could be an issue related to the FileProvider, closing because stale for so long
