### ISSUE TITLE
ModelTableHeader not working?

### ISSUE THREAD

**Issue by nanduk667** [kariot/pdf-invoice-generator#5]
The result seems to be always with default C1,C2..values. even in the example.
A fix would be helpful. Thanks

**Comment by kariot** [comment]
I'll look in to the issue, thanks for your patience

**Comment by HridaySarma** [comment]
Yes please look into that i am facing the same issue

**Comment by cstar-99** [comment]
yeah I'm having same issue, please tell us the solution

**Comment by cstar-99** [comment]
![Screenshot (3)_LI](https://user-images.githubusercontent.com/57938939/165930136-d5c44b8e-5448-4dd6-8343-1000cf9426a9.jpg)

Please just replace that name with the function parameter. Please do this update fast

**Comment by aeiou-st** [comment]
Thank you for solving this issue.

> yeah I'm having same issue, please tell us the solution

**Comment by kariot** [comment]
The issue has been fixed in PR #6
